required = ["github.com/revel/cmd", "github.com/revel/modules"]

[[constraint]]
  branch = "master"
  name = "github.com/koofr/go-koofrclient"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/revel/cmd"
  version = "0.20.0"

[[constraint]]
  name = "github.com/revel/modules"
  version = "0.20.1"

[[constraint]]
  name = "github.com/revel/revel"
  version = "0.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "github.com/revel/modules"
  unused-packages = false
